#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright (c) 2018 RS Components Ltd
# SPDX-License-Identifier: Apache License 2.0

import sys
import time
import json
import yaml
import zmq
import signal

import paho.mqtt.publish as publish

from web3 import Web3, HTTPProvider
from web3.contract import ConciseContract
from web3.middleware import geth_poa_middleware

from DesignSpark.Pmod.HAT import createPmod
from luma.core.render import canvas
from luma.oled.device import ssd1331
from PIL import ImageFont

with open("/opt/iotbc/etc/config.yml", 'r') as ymlfile:
    cfg = yaml.load(ymlfile)

with open("/opt/iotbc/etc/TemperatureAlertABI.json", 'r') as f:
    abi = json.load(f)

device = cfg['application']['role']
max_temp = cfg['application']['max_temp']
leds_port = cfg['application']['leds_port']
broker = cfg['mqtt']['broker']
account = cfg['blockchain']['account']
contract = cfg['blockchain']['contract']

# Ethereum

w3 = Web3(HTTPProvider('http://127.0.0.1:8545'))
w3.middleware_stack.inject(geth_poa_middleware, layer=0)

TemperatureAlert = w3.eth.contract(
    contract, abi=abi, ContractFactoryClass=ConciseContract)

def IoTBCwrite(data):
    TemperatureAlert.setOverTemperature(int(data), transact={'from': account})


# Gracefully exit

class GracefulKiller:
    kill_now = False
    def __init__(self):
        signal.signal(signal.SIGINT, self.exit_gracefully)
        signal.signal(signal.SIGTERM, self.exit_gracefully)

    def exit_gracefully(self,signum, frame):
        self.kill_now = True


# Main

if __name__ == '__main__':

    therm = createPmod('TC1','JBA')

    context = zmq.Context()
    leds = context.socket(zmq.PAIR)
    leds.connect("tcp://localhost:%s" % leds_port)

    oled = createPmod('OLEDrgb','JA')
    display = oled.getDevice()
    font = ImageFont.truetype("FreeMonoBold.ttf", 26, encoding="unic")

    killer = GracefulKiller()

    while True:
        cel = int(therm.readCelcius())

        if cel > max_temp:
            print('Temperature alert! Reached: {0}C'.format(cel))

            with canvas(display) as draw:
                draw.rectangle(display.bounding_box, outline="red", fill="black")
                draw.text((16,20), '{0}C'.format(cel), fill="red", font=font)

            try:
                publish.single('iotbc/{0}'.format(device), cel, hostname=broker, client_id=device)
            except:
                print('Failed to publish to MQTT broker')

            try:
                IoTBCwrite(cel)
                leds.send_string('red,0.05,20')
            except:
                print('Failed to write to blockchain')

            time.sleep(15)

        else:
            with canvas(display) as draw:
                draw.rectangle(display.bounding_box, outline="green", fill="black")
                draw.text((16,20), '{0}C'.format(cel), fill="green", font=font)

            time.sleep(0.2)

        if killer.kill_now:
            break

        time.sleep(1)
